

# This file was *autogenerated* from the file linkgfcbatch.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_9 = Integer(9)
from CodeModules.cinfprocessing import *
import CodeModules.GFKTools as gfk

import sys

index = sys.argv[_sage_const_1 ]

link_dict_partition = gfk.imp_from_pickle(f"./Pickles/sub_dict{index}.pickle")

for link in link_dict_partition:
    if len(link_dict_partition[link][_sage_const_0 ]) < _sage_const_9 :
        reduced_comp = link_GFC(*link_dict_partition[link], link)
        gfk.pickle_it(reduced_comp, link + ".pickle")

